# Generated by Django 3.0.8 on 2020-11-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='stats/imagess/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
