# Generated by Django 3.0.8 on 2020-11-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('img', models.ImageField(upload_to='stats/images/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='resources',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='resources',
            name='img',
            field=models.ImageField(upload_to='stats/images/'),
        ),
    ]
